In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
print a

[1 2 3 4]


In [12]:
import time
b = np.random.rand(1000000)
c = np.random.rand(1000000)
t1 = time.time()
d = np.dot(b,c)
t2 = time.time()
print "Vectioriation method : {} ms".format((t2-t1)*1000)
print d
t3 = time.time()
sum = 0
for i in range(1000000):
    sum += b[i]*c[i]
t4 = time.time()
print "Loop method : {} ms".format((t4-t3)*1000)
print d

Vectioriation method : 7.99989700317 ms
250082.19597
Loop method : 1091.00008011 ms
250082.19597


In [13]:
e = [1,2,3,4,5]

In [14]:
f = np.zeros((5,1))

In [15]:
import math
for i in range(5):
    f[i] = math.exp(e[i])

In [16]:
print f

[[   2.71828183]
 [   7.3890561 ]
 [  20.08553692]
 [  54.59815003]
 [ 148.4131591 ]]


In [17]:
g = np.exp(e)

In [18]:
g

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ])

In [19]:
h = np.log(e)

In [20]:
h

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791])

In [21]:
i = np.max(e)

In [22]:
i

5

In [23]:
j = np.min(e)

In [24]:
j

1

In [25]:
k = np.abs(e)

In [26]:
k

array([1, 2, 3, 4, 5])